### ISSUE TITLE
Issue with Too Many Items in Details Pane Not Fitting

### ISSUE THREAD

**Issue by burnpsy** [eminaguil/eMixedNite#5]
This is probably an edge case, but here goes:

I currently use eMixedNite in grid view with a large Details pane that takes half of my window. This is fine 99% of the time, but for a handful of my games the add-on integration leads to stuff not fitting on the screen.

In this example, I used DuplicateHider to group the entire Hitman World of Assassination trilogy, and I own Hitman 2016 twice, leading to 4 platforms and the completion status going off the screen like so:
![2021-11-15 (1)](https://user-images.githubusercontent.com/6007819/141890759-8a933193-7440-42c9-b372-55b686127253.png)
Only the flag is now visible.

A similar thing happens if a game has too many links, the links continue off the edge of the details pane, where I can no longer click them.

I don't know what can be done to avoid this, but if I can make a suggestion maybe making additional rows if it would go off the edge?

**Comment by eminaguil** [comment]
Fixed in v2.60
