### ISSUE TITLE
Q: Where does the theme store completion status icons?

### ISSUE THREAD

**Issue by coreyemtp** [eminaguil/eMixedNite#8]
...and, is it possible to change them? Set an icon for an added (custom) completion status?

Thanks!

**Comment by eminaguil** [comment]
Hi.

The icons are part of the font used by Playnite, you can change them only by editing the constant file in the theme installation folder.

The lines where it can be changed are:
[Constants.xaml](https://github.com/eminaguil/eMixedNite/blob/main/source/Constants.xaml#L85)

The font can be downloaded here, and from windows charmap you can copy to the file.
[icofont](https://github.com/eminaguil/eMixedNite/tree/main/source/Fonts)

**Comment by coreyemtp** [comment]
Thank you for the quick response! That's perfect.
